name: Setup python
description: "Sets up python"

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'poetry'
      - run: poetry install
        shell: bash
      - run: sudo apt-get update
        shell: bash
      - run: sudo apt-get install git-crypt
        shell: bash
      - run: echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt.key
        shell: bash
      - run: git-crypt unlock ./git-crypt.key
        shell: bash
