name: Poetry CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run ruff format .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run ruff check --fix .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run pyright .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run pytest
