name: Poetry CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - name: Install deps
        run: poetry install

  format:
    runs-on: ubuntu-latest
    container:
      image: node:18
      volumes:
        - my_docker_volume:/volume_mount
    needs: build
    steps:
      - run: poetry run ruff format .

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
      volumes:
        - my_docker_volume:/volume_mount
    needs: build
    steps:
      - run: poetry run ruff check --fix .

  typecheck:
    runs-on: ubuntu-latest
    container:
      image: node:18
      volumes:
        - my_docker_volume:/volume_mount
    needs: build
    steps:
      - run: poetry run pyright .

  test:
    runs-on: ubuntu-latest
    container:
      image: node:18
      volumes:
        - my_docker_volume:/volume_mount
    needs: build
    steps:
      - run: poetry run pytest
