name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python
      - run: poetry run ruff format .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python
      - run: poetry run ruff check --fix .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python
      - run: poetry run pyright .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python
      - run: poetry run pytest
